---
apiVersion: v1
kind: ConfigMap
metadata:
  name: packagemanage-config
data:
  conf.yaml: |
    - dbname: openeuler-21.03
      src_db_file: https://repo.openeuler.org/openEuler-21.03/source
      bin_db_file: https://repo.openeuler.org/openEuler-21.03/everything/aarch64
      priority: 1

    - dbname: openeuler-20.03-lts-sp1
      src_db_file: https://repo.openeuler.org/openEuler-20.03-LTS-SP1/source
      bin_db_file: https://repo.openeuler.org/openEuler-20.03-LTS-SP1/everything/aarch64
      priority: 2

    - dbname: openeuler-20.09
      src_db_file: https://repo.openeuler.org/openEuler-20.09/source
      bin_db_file: https://repo.openeuler.org/openEuler-20.09/everything/aarch64
      priority: 3

    - dbname: openeuler-20.03-lts
      src_db_file: https://repo.openeuler.org/openEuler-20.03-LTS/source
      bin_db_file: https://repo.openeuler.org/openEuler-20.03-LTS/everything/aarch64
      priority: 4

    - dbname: fedora33
      src_db_file: https://mirrors.huaweicloud.com/fedora/releases/33/Everything/source/tree/
      bin_db_file: https://mirrors.huaweicloud.com/fedora/releases/33/Everything/aarch64/os/
      priority: 5
  package.ini: |
    [SYSTEM]
    ; Configuration file path for data initialization
    init_conf_path=/etc/pkgship/conf.yaml
    
    ; Ordinary user query port, only the right to query data, no permission to write data
        
    query_port=8090
    
    ; IP address path with permission to query data
    
    query_ip_addr=0.0.0.0
    
    ; The address of the remote service, the command line can directly 
    ; call the remote service to complete the data request
    remote_host=https://api.openeuler.org/pkgmanage
    
    ; A temporary directory for files downloaded from the network that are cleaned periodically
    ; The recommended free space in this dir is 1G
    temporary_directory=/opt/pkgship/tmp/
    
    [LOG]
    ; Custom log storage path
    log_path=/var/log/pkgship/
    
    ; Logging level
    ; The log level option value can only be as follows
    ; INFO DEBUG WARNING ERROR CRITICAL
    log_level=INFO
    
    ; Maximum capacity of each file, the unit is byte, default is 30M
    max_bytes=31457280
    
    ; Number of old logs to keep;default is 30
    backup_count=30
    
    [UWSGI]
    ; Operation log storage path
    daemonize=/var/log/pkgship-operation/uwsgi.log
    ; The data size transferred from back to forth
    buffer-size=65536
    ; HTTP Connection time
    http-timeout=600
    ; Server response time
    harakiri=600
    
    [REDIS]
    ;The address of the Redis cache server can be either a published
    ;domain or an IP address that can be accessed normally
    ;The link address defaults to 127.0.0.1
    redis_host=127.0.0.1
    
    ;Redis cache server link port number, default is 6379
    redis_port=6379
    
    ;Maximum number of connections allowed by RedIS server at one time
    redis_max_connections=10
    
    [DATABASE]
    ;The database engines supported in the system is sqlite database by default
    database_engine_type=elastic
    
    ;Default ip address of database
    database_host=127.0.0.1
    
    ;Default port of database
    database_port=9200
