# Deployment for packagemanage service
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: package-manage-server
spec:
  selector:
    matchLabels:
      comp: package-manage
  template:
    metadata:
      labels:
        comp: package-manage
    spec:
      initContainers:
        - name: database-init
          image: opensourceway/dbgetinit:v1.0
          volumeMounts:
            - mountPath: /etc/database
              name: database-volume
          command:
            - /bin/sh
            - -c
            - |
              python3 getsqlitefileTemp.py "https://gitee.com/ruebb/pkgship_sqlite_file" "/etc/database"
              cd /etc/database
              touch $(date "+%Y-%m-%d_%H:%M:%S").time
      containers:
        - name: pkg-manage-server
          image: opensourceway/packagemanage:v2.0
          volumeMounts:
            - mountPath: /etc/database
              name: database-volume
            - mountPath: /etc/pkgship/conf.yaml
              name: pkgmanage-config-volume
              subPath: conf.yaml
            - mountPath: /etc/pkgship/package.ini
              name: pkgmanage-config-volume
              subPath: package.ini
          resources:
            requests:
              cpu: 2000m
              memory: 2000Mi
          command:
            - /bin/sh
            - -c
            - |
              pkgshipd start;
              pkgship init;
              pkgship update --package;
              pkgship update --issue;
              redis-server /etc/redis.conf
              sleep infinity
      volumes:
        - name: pkgmanage-config-volume
          configMap:
            name: packagemanage-config
        - name: database-volume
          persistentVolumeClaim:
            claimName: openeuler-pkgship-db-volume

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: package-manage-web
spec:
  selector:
    matchLabels:
      comp: package-manage-web
  template:
    metadata:
      labels:
        comp: package-manage-web
    spec:
      containers:
        - name: pkgmanagewebui
          image: opensourceway/pkgmanageweb:v1.0
          resources:
            requests:
              cpu: 2000m
              memory: 2000Mi

